{{- /* Create secret only when apiToken is provided and not using external secret */ -}}
{{- if and (not .Values.cloudflare.apiTokenSecretName) (or .Values.cloudflare.apiToken (and .Values.manageCloudflared.enabled .Values.manageCloudflared.tunnelToken)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cf-tunnel-gw-ctrl.fullname" . }}
  labels:
    {{- include "cf-tunnel-gw-ctrl.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.cloudflare.apiToken (ne .Values.cloudflare.apiToken "") }}
  api-token: {{ .Values.cloudflare.apiToken | b64enc | quote }}
  {{- end }}
  {{- if and .Values.manageCloudflared.enabled .Values.manageCloudflared.tunnelToken (not .Values.manageCloudflared.tunnelTokenSecretName) (ne .Values.manageCloudflared.tunnelToken "") }}
  tunnel-token: {{ .Values.manageCloudflared.tunnelToken | b64enc | quote }}
  {{- end }}
{{- end }}
